export const SET_PRODUCTS_REQUESTED = "SET_PRODUCTS_REQUESTED";
export const SET_PRODUCTS_FILTERED_REQUESTED = "SET_PRODUCTS_FILTERED_REQUESTED";
export const SET_PRODUCTS_SUCCESS = "SET_PRODUCTS_SUCCESS";
export const SET_PRODUCTS_FILTERED_SUCCESS = "SET_PRODUCTS_FILTERED_SUCCESS";
export const SET_PRODUCTS_FAILED = "SET_PRODUCTS_FAILED";